### ISSUE TITLE
X-Cart-5 Plugin

### ISSUE THREAD

**Issue by nurulazliyana** [RazerMS/Shopping-Cart-Plugins-RazerMS-X-Cart#1]
Merchant legkick request for add seamless plugin under reason required due to multicurrency channel.
Due date : 02-March-2019

**Comment by wankimmy** [comment]
Hi @nurulazliyana , Apologies we have not been active in Github platform in the past to reply issues, if there is still anything we are able to help kindly reply to this issue, else we will proceed to close the issue if receive no reply. Rest assured you are still welcome to raise any issue in the future
